// <auto-generated />
using System;
using AcadionApi.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcadionApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930072651_TurnosExamenFinalInstitucionales")]
    partial class TurnosExamenFinalInstitucionales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Allegado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("NombreApellido")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Relacion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId", "NombreApellido");

                    b.ToTable("Allegados");
                });

            modelBuilder.Entity("Anio", b =>
                {
                    b.Property<int>("IdAnio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnio"));

                    b.Property<int>("IdCarrera")
                        .HasColumnType("int");

                    b.Property<string>("NombreAnio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroAnio")
                        .HasColumnType("int");

                    b.HasKey("IdAnio");

                    b.HasIndex("IdCarrera", "NumeroAnio")
                        .IsUnique();

                    b.ToTable("Anio");
                });

            modelBuilder.Entity("Asistencia", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistencia"));

                    b.Property<int>("CantidadInasistencias")
                        .HasColumnType("int");

                    b.Property<int?>("ClaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudianteMateria")
                        .HasColumnType("int");

                    b.Property<bool>("Justificada")
                        .HasColumnType("bit");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemaDictado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoClase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("ClaseId");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdEstudianteMateria", "Fecha")
                        .IsUnique();

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrera"));

                    b.Property<int>("CapacidadMaximaEstudiantes")
                        .HasColumnType("int");

                    b.Property<int>("DuracionAnios")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PlanEstudios")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdCarrera");

                    b.HasIndex("Nombre", "PlanEstudios")
                        .IsUnique();

                    b.ToTable("Carrera");
                });

            modelBuilder.Entity("ClaseAcademica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AulaOEnlace")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("ComisionId")
                        .HasColumnType("int");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ComisionId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("MateriaId", "ComisionId", "Fecha")
                        .IsUnique()
                        .HasFilter("[ComisionId] IS NOT NULL");

                    b.ToTable("ClasesAcademicas");
                });

            modelBuilder.Entity("Comision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("CicloLectivo")
                        .HasColumnType("int");

                    b.Property<int>("Cupo")
                        .HasColumnType("int");

                    b.Property<int?>("DocenteId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("MateriaId", "CicloLectivo", "Nombre")
                        .IsUnique();

                    b.ToTable("Comisiones");
                });

            modelBuilder.Entity("CuotaMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("ComprobanteUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaValidacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ValidadoPorUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ValidadoPorUsuarioId");

                    b.HasIndex("EstudianteId", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("CuotasMensuales");
                });

            modelBuilder.Entity("DocenteMateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("CicloLectivo")
                        .HasColumnType("int");

                    b.Property<string>("Cuatrimestre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaAsignacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdDocente", "IdMateria", "CicloLectivo", "Cuatrimestre")
                        .IsUnique();

                    b.ToTable("DocentesMaterias");
                });

            modelBuilder.Entity("EquivalenciaMateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaOtorgamientoUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MateriaDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaOrigenId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OtorgadaPorUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaDestinoId");

                    b.HasIndex("MateriaOrigenId");

                    b.HasIndex("OtorgadaPorUsuarioId");

                    b.HasIndex("EstudianteId", "MateriaDestinoId")
                        .IsUnique();

                    b.ToTable("EquivalenciasMaterias");
                });

            modelBuilder.Entity("EstudianteMateria", b =>
                {
                    b.Property<int>("IdEstudianteMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudianteMateria"));

                    b.Property<int>("CicloLectivo")
                        .HasColumnType("int");

                    b.Property<int?>("ComisionId")
                        .HasColumnType("int");

                    b.Property<string>("Cuatrimestre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdDocente")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.HasKey("IdEstudianteMateria");

                    b.HasIndex("ComisionId");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdEstudiante", "IdMateria", "CicloLectivo")
                        .IsUnique();

                    b.ToTable("EstudianteMaterias");
                });

            modelBuilder.Entity("EventoCalendario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CarreraId")
                        .HasColumnType("int");

                    b.Property<int>("CreadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFinUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicioUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("FechaInicioUtc", "FechaFinUtc");

                    b.ToTable("EventosCalendario");
                });

            modelBuilder.Entity("Examen", b =>
                {
                    b.Property<int>("IdExamen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExamen"));

                    b.Property<int>("CicloLectivo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.Property<decimal?>("NotaMinimaPromocion")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("NotaMinimaRegularizacion")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("TipoExamen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TurnoExamenFinalId")
                        .HasColumnType("int");

                    b.HasKey("IdExamen");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdMateria");

                    b.HasIndex("TurnoExamenFinalId");

                    b.ToTable("Examen");
                });

            modelBuilder.Entity("HorarioComision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComisionId")
                        .HasColumnType("int");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ComisionId");

                    b.ToTable("HorariosComisiones");
                });

            modelBuilder.Entity("HorarioMateria", b =>
                {
                    b.Property<int>("IdHorarioMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorarioMateria"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.HasKey("IdHorarioMateria");

                    b.HasIndex("IdMateria");

                    b.ToTable("HorarioMateria");
                });

            modelBuilder.Entity("InscripcionExamen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("ExamenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInscripcionUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("ExamenId", "EstudianteId")
                        .IsUnique();

                    b.ToTable("InscripcionesExamenes");
                });

            modelBuilder.Entity("ListaEsperaComision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComisionId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaResolucionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitudUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResueltoPorUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("ResueltoPorUsuarioId");

                    b.HasIndex("ComisionId", "EstudianteId")
                        .IsUnique();

                    b.ToTable("ListasEsperaComisiones");
                });

            modelBuilder.Entity("Materia", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMateria"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAnio")
                        .HasColumnType("int");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroPeriodo")
                        .HasColumnType("int");

                    b.Property<int?>("PlanEstudioId")
                        .HasColumnType("int");

                    b.Property<string>("TipoCursada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMateria");

                    b.HasIndex("IdAnio");

                    b.HasIndex("PlanEstudioId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("MateriaCorrelativa", b =>
                {
                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.Property<int>("IdCorrelativa")
                        .HasColumnType("int");

                    b.HasKey("IdMateria", "IdCorrelativa");

                    b.HasIndex("IdCorrelativa");

                    b.ToTable("MateriaCorrelativa", (string)null);
                });

            modelBuilder.Entity("MatriculaInicial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComprobanteUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaValidacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PeriodoLectivo")
                        .HasColumnType("int");

                    b.Property<int?>("ValidadoPorUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ValidadoPorUsuarioId");

                    b.HasIndex("EstudianteId", "PeriodoLectivo")
                        .IsUnique();

                    b.ToTable("MatriculasIniciales");
                });

            modelBuilder.Entity("NotaExamen", b =>
                {
                    b.Property<int>("IdNota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNota"));

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<int>("IdExamen")
                        .HasColumnType("int");

                    b.Property<decimal>("Nota")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNota");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdExamen", "IdEstudiante")
                        .IsUnique();

                    b.ToTable("NotaExamen");
                });

            modelBuilder.Entity("NotificacionGeneral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("ClaveAutomatica")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int?>("CreadaPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaExpiracionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPublicacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolDestinoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioDestinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaveAutomatica")
                        .IsUnique()
                        .HasFilter("[ClaveAutomatica] IS NOT NULL");

                    b.HasIndex("CreadaPorUsuarioId");

                    b.HasIndex("RolDestinoId");

                    b.HasIndex("UsuarioDestinoId");

                    b.ToTable("NotificacionesGenerales");
                });

            modelBuilder.Entity("PerfilFinanciamiento", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("AporteFamiliares")
                        .HasColumnType("bit");

                    b.Property<bool>("Beca")
                        .HasColumnType("bit");

                    b.Property<bool>("OtraFuente")
                        .HasColumnType("bit");

                    b.Property<bool>("PlanesSociales")
                        .HasColumnType("bit");

                    b.Property<bool>("Trabajo")
                        .HasColumnType("bit");

                    b.HasKey("UsuarioId");

                    b.ToTable("PerfilesFinanciamiento");
                });

            modelBuilder.Entity("PeriodoInscripcionExamen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CicloLectivo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFinUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicioUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModificadoPorUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CicloLectivo")
                        .IsUnique();

                    b.HasIndex("ModificadoPorUsuarioId");

                    b.ToTable("PeriodosInscripcionExamenes");
                });

            modelBuilder.Entity("PeriodoInscripcionMateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<int>("CicloLectivo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFinUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicioUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificadoPorUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModificadoPorUsuarioId");

                    b.HasIndex("CarreraId", "CicloLectivo")
                        .IsUnique()
                        .HasFilter("[MateriaId] IS NULL");

                    b.HasIndex("MateriaId", "CicloLectivo")
                        .IsUnique()
                        .HasFilter("[MateriaId] IS NOT NULL");

                    b.ToTable("PeriodosInscripcionMaterias");
                });

            modelBuilder.Entity("Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "usuarios.leer",
                            Descripcion = "Consultar usuarios."
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "usuarios.gestionar",
                            Descripcion = "Crear y administrar cuentas."
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "academico.leer",
                            Descripcion = "Consultar carreras, años y materias."
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "academico.gestionar",
                            Descripcion = "Administrar la estructura académica."
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "inscripciones.propias.leer",
                            Descripcion = "Consultar sus materias."
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "inscripciones.gestionar",
                            Descripcion = "Administrar inscripciones y asignaciones."
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "docencia.gestionar",
                            Descripcion = "Gestionar las comisiones asignadas."
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "asistencias.propias.leer",
                            Descripcion = "Consultar sus asistencias."
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "asistencia-personal.gestionar",
                            Descripcion = "Registrar fichado del personal."
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "examenes.propios.leer",
                            Descripcion = "Consultar sus evaluaciones."
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "notas.propias.leer",
                            Descripcion = "Consultar sus calificaciones."
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "reportes.leer",
                            Descripcion = "Consultar reportes institucionales."
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "notificaciones.gestionar",
                            Descripcion = "Publicar y administrar notificaciones generales."
                        });
                });

            modelBuilder.Entity("Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Dni")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("PlanEstudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("VigenteDesde")
                        .HasColumnType("int");

                    b.Property<int?>("VigenteHasta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId", "Activo");

                    b.HasIndex("CarreraId", "Codigo")
                        .IsUnique();

                    b.ToTable("PlanesEstudio");
                });

            modelBuilder.Entity("RecuperacionContrasena", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaExpiracionTokenUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUsoUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVerificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<string>("TokenHash")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .HasFilter("[TokenHash] IS NOT NULL");

                    b.HasIndex("UsuarioId", "FechaExpiracionUtc");

                    b.ToTable("RecuperacionesContrasena");
                });

            modelBuilder.Entity("RegistroAsistenciaPersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly?>("HoraEntrada")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<bool>("Justificada")
                        .HasColumnType("bit");

                    b.Property<int?>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistradoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("RegistradoPorUsuarioId");

                    b.HasIndex("UsuarioId", "Fecha")
                        .IsUnique()
                        .HasFilter("[MateriaId] IS NULL");

                    b.HasIndex("UsuarioId", "MateriaId", "Fecha")
                        .IsUnique()
                        .HasFilter("[MateriaId] IS NOT NULL");

                    b.ToTable("RegistrosAsistenciaPersonal");
                });

            modelBuilder.Entity("RegistroAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("EstadoHttp")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("UsuarioId", "FechaUtc");

                    b.ToTable("RegistrosAuditoria");
                });

            modelBuilder.Entity("Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Acceso únicamente a su información académica.",
                            Nombre = "Estudiante"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Gestión de sus comisiones, asistencias, evaluaciones y notas.",
                            Nombre = "Docente"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Administración académica y de cuentas institucionales.",
                            Nombre = "Secretario"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Consulta institucional y reportes.",
                            Nombre = "Directivo"
                        });
                });

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolesPermisos");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            PermisoId = 5
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 8
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 10
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 11
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 3
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 7
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 2
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 3
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 4
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 5
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 6
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 7
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 8
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 9
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 10
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 11
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 12
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 13
                        },
                        new
                        {
                            RolId = 4,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 4,
                            PermisoId = 3
                        },
                        new
                        {
                            RolId = 4,
                            PermisoId = 12
                        });
                });

            modelBuilder.Entity("TurnoExamenFinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CicloLectivo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFinUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicioUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("NumeroLlamado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CicloLectivo", "Nombre", "NumeroLlamado")
                        .IsUnique();

                    b.ToTable("TurnosExamenFinal");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarreraId")
                        .HasColumnType("int");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("bit");

                    b.Property<string>("EmailInstitucional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPerfilUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int?>("PlanEstudioId")
                        .HasColumnType("int");

                    b.Property<double>("PromedioGeneral")
                        .HasColumnType("float");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("Rol");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TituloAcademico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("Legajo")
                        .IsUnique()
                        .HasFilter("[Legajo] <> ''");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("PersonaId");

                    b.HasIndex("PlanEstudioId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Allegado", b =>
                {
                    b.HasOne("Usuario", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("Anio", b =>
                {
                    b.HasOne("Carrera", "Carrera")
                        .WithMany("AniosAcademicos")
                        .HasForeignKey("IdCarrera")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("Asistencia", b =>
                {
                    b.HasOne("ClaseAcademica", "Clase")
                        .WithMany("Asistencias")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Usuario", "Docente")
                        .WithMany()
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstudianteMateria", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("IdEstudianteMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Docente");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("ClaseAcademica", b =>
                {
                    b.HasOne("Comision", "Comision")
                        .WithMany()
                        .HasForeignKey("ComisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Usuario", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comision");

                    b.Navigation("Docente");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("Comision", b =>
                {
                    b.HasOne("Usuario", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Materia", "Materia")
                        .WithMany("Comisiones")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("CuotaMensual", b =>
                {
                    b.HasOne("Usuario", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario", "ValidadoPor")
                        .WithMany()
                        .HasForeignKey("ValidadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estudiante");

                    b.Navigation("ValidadoPor");
                });

            modelBuilder.Entity("DocenteMateria", b =>
                {
                    b.HasOne("Usuario", "Docente")
                        .WithMany()
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("EquivalenciaMateria", b =>
                {
                    b.HasOne("Usuario", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Materia", "MateriaDestino")
                        .WithMany()
                        .HasForeignKey("MateriaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Materia", "MateriaOrigen")
                        .WithMany()
                        .HasForeignKey("MateriaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Usuario", "OtorgadaPor")
                        .WithMany()
                        .HasForeignKey("OtorgadaPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("MateriaDestino");

                    b.Navigation("MateriaOrigen");

                    b.Navigation("OtorgadaPor");
                });

            modelBuilder.Entity("EstudianteMateria", b =>
                {
                    b.HasOne("Comision", "Comision")
                        .WithMany("Inscripciones")
                        .HasForeignKey("ComisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Usuario", "Docente")
                        .WithMany()
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Usuario", "Estudiante")
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comision");

                    b.Navigation("Docente");

                    b.Navigation("Estudiante");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("EventoCalendario", b =>
                {
                    b.HasOne("Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("Examen", b =>
                {
                    b.HasOne("Usuario", "Docente")
                        .WithMany()
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnoExamenFinal", "TurnoExamenFinal")
                        .WithMany("Examenes")
                        .HasForeignKey("TurnoExamenFinalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Docente");

                    b.Navigation("Materia");

                    b.Navigation("TurnoExamenFinal");
                });

            modelBuilder.Entity("HorarioComision", b =>
                {
                    b.HasOne("Comision", "Comision")
                        .WithMany("Horarios")
                        .HasForeignKey("ComisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comision");
                });

            modelBuilder.Entity("HorarioMateria", b =>
                {
                    b.HasOne("Materia", null)
                        .WithMany("Horarios")
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InscripcionExamen", b =>
                {
                    b.HasOne("Usuario", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Examen", "Examen")
                        .WithMany()
                        .HasForeignKey("ExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Examen");
                });

            modelBuilder.Entity("ListaEsperaComision", b =>
                {
                    b.HasOne("Comision", "Comision")
                        .WithMany("ListaEspera")
                        .HasForeignKey("ComisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Usuario", "ResueltoPor")
                        .WithMany()
                        .HasForeignKey("ResueltoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Comision");

                    b.Navigation("Estudiante");

                    b.Navigation("ResueltoPor");
                });

            modelBuilder.Entity("Materia", b =>
                {
                    b.HasOne("Anio", "AnioCursada")
                        .WithMany("Materias")
                        .HasForeignKey("IdAnio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanEstudio", "PlanEstudio")
                        .WithMany("Materias")
                        .HasForeignKey("PlanEstudioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AnioCursada");

                    b.Navigation("PlanEstudio");
                });

            modelBuilder.Entity("MateriaCorrelativa", b =>
                {
                    b.HasOne("Materia", null)
                        .WithMany()
                        .HasForeignKey("IdCorrelativa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Materia", null)
                        .WithMany()
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MatriculaInicial", b =>
                {
                    b.HasOne("Usuario", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario", "ValidadoPor")
                        .WithMany()
                        .HasForeignKey("ValidadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estudiante");

                    b.Navigation("ValidadoPor");
                });

            modelBuilder.Entity("NotaExamen", b =>
                {
                    b.HasOne("Usuario", "Estudiante")
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Examen", "Examen")
                        .WithMany("Notas")
                        .HasForeignKey("IdExamen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Examen");
                });

            modelBuilder.Entity("NotificacionGeneral", b =>
                {
                    b.HasOne("Usuario", "CreadaPor")
                        .WithMany()
                        .HasForeignKey("CreadaPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Rol", "RolDestino")
                        .WithMany()
                        .HasForeignKey("RolDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Usuario", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("UsuarioDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreadaPor");

                    b.Navigation("RolDestino");

                    b.Navigation("UsuarioDestino");
                });

            modelBuilder.Entity("PerfilFinanciamiento", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("PerfilFinanciamiento", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PeriodoInscripcionExamen", b =>
                {
                    b.HasOne("Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModificadoPor");
                });

            modelBuilder.Entity("PeriodoInscripcionMateria", b =>
                {
                    b.HasOne("Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Carrera");

                    b.Navigation("Materia");

                    b.Navigation("ModificadoPor");
                });

            modelBuilder.Entity("PlanEstudio", b =>
                {
                    b.HasOne("Carrera", "Carrera")
                        .WithMany("PlanesEstudio")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("RecuperacionContrasena", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("RecuperacionesContrasena")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RegistroAsistenciaPersonal", b =>
                {
                    b.HasOne("Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("RegistradoPor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.HasOne("Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.HasOne("Carrera", "Carrera")
                        .WithMany("AlumnosInscritos")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanEstudio", "PlanEstudio")
                        .WithMany("Estudiantes")
                        .HasForeignKey("PlanEstudioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Persona");

                    b.Navigation("PlanEstudio");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Anio", b =>
                {
                    b.Navigation("Materias");
                });

            modelBuilder.Entity("Carrera", b =>
                {
                    b.Navigation("AlumnosInscritos");

                    b.Navigation("AniosAcademicos");

                    b.Navigation("PlanesEstudio");
                });

            modelBuilder.Entity("ClaseAcademica", b =>
                {
                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("Comision", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("Inscripciones");

                    b.Navigation("ListaEspera");
                });

            modelBuilder.Entity("Examen", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("Materia", b =>
                {
                    b.Navigation("Comisiones");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("PlanEstudio", b =>
                {
                    b.Navigation("Estudiantes");

                    b.Navigation("Materias");
                });

            modelBuilder.Entity("Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TurnoExamenFinal", b =>
                {
                    b.Navigation("Examenes");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("RecuperacionesContrasena");
                });
#pragma warning restore 612, 618
        }
    }
}
